server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://47.120.38.17:3306/banking_system?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 12345As#
    driver-class-name: com.mysql.cj.jdbc.Driver